### ISSUE TITLE
配合最新版思源1.3.5时会出现bug

### ISSUE THREAD

**Issue by leolee9086** [siyuan-note/siyuan-chrome#2]
会显示下面的提示
![TME2HE1U$(0V%HSB6TM }1K](https://user-images.githubusercontent.com/19915077/134279970-cd43e77f-6c4d-482e-94e8-780ad33a63d8.png)
好像是这里的问题
![image](https://user-images.githubusercontent.com/19915077/134280023-0227221a-c125-4892-8912-33ff7ab79aba.png)
popup.js第69行开始的`response.data.notebooks`好像应该是response.data.files，改了这里之后正常了

**Comment by 88250** [comment]
`.notebooks` 是正确的，等发版。
