### ISSUE TITLE
siyuan v1.5.4无法使用网页剪藏

### ISSUE THREAD

**Issue by grace-gu** [siyuan-note/siyuan-chrome#4]
背景：
1. mac，siyuan1.5.4
![image](https://user-images.githubusercontent.com/15803404/146736104-bb41717f-222d-4d86-b1da-bf285464209b.png)

2. chrome已安装siyuan插件，配置了API
![image](https://user-images.githubusercontent.com/15803404/146736000-44281678-574d-41f1-a010-c569fca14345.png)

采用了两种方式均无效。
操作详情一：
在 Web 页面上选择需要剪藏的内容，然后在右键菜单中选择 “Copy to SiYuan”，网页中会提示：
![image](https://user-images.githubusercontent.com/15803404/146736500-5ab112a9-ab86-4d88-99e1-6af3635aa755.png)
但在思源中粘贴时，会显示更之前的复制内容

操作详情二：
直接在chrome插件中点击Send to SiYuan，会无事发生
![image](https://user-images.githubusercontent.com/15803404/146736636-a1fe7bef-2589-487d-9a32-56eb31e174d0.png)

**Comment by 88250** [comment]
麻烦发一下网页 URL。

**Comment by grace-gu** [comment]
> 

所有网页均有此问题，包括baidu，github, google, CSDN等等

**Comment by 88250** [comment]
我这里在开发版上试了下暂时无法重现，请等下一个版本发布以后再试试。或者我拉你进内测，帮忙测试一下好吗？

**Comment by grace-gu** [comment]
好的，那拉我进内测群吧

**Comment by 88250** [comment]
已经邀请，内测仓库 https://github.com/siyuan-note/insider 请注意备份数据并关注发版信息，谢谢。

**Comment by 88250** [comment]
我关闭了，如果还有问题麻烦反馈，谢谢。
