### ISSUE TITLE
网页剪藏的时候，如果是代码，会在最下面追加一堆数字

### ISSUE THREAD

**Issue by YorickGu** [siyuan-note/siyuan-chrome#6]
![image](https://user-images.githubusercontent.com/34763540/149910519-fa593ff9-4e4f-4e26-b6ea-04b0dc31db86.png)

**Comment by 88250** [comment]
麻烦发一下这个网页地址，后续改进请关注 https://github.com/siyuan-note/siyuan/issues/3266

**Comment by YorickGu** [comment]
> 麻烦发一下这个网页地址，后续改进请关注 [siyuan-note/siyuan#3266](https://github.com/siyuan-note/siyuan/issues/3266)

https://blog.csdn.net/weixin_37778801/article/details/86286817
